version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - default-network
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
    restart: always
    depends_on:
      - db
    command: >
      sh -c "npm run boot && node index.js"

  db:
    image: postgres
    restart: always
    networks:
      - default-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:

networks:
  default-network: