name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Cache Firebase Tools
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase
          key: ${{ runner.os }}-firebase-tools
          restore-keys: |
            ${{ runner.os }}-firebase-tools

      - name: Install Firebase Tools
        run: |
          if [ ! -d "~/.cache/firebase" ]; then
            npm install -g firebase-tools
            mkdir -p ~/.cache/firebase
            cp -r /usr/local/lib/node_modules/firebase-tools ~/.cache/firebase
          else
            cp -r ~/.cache/firebase/firebase-tools /usr/local/lib/node_modules/firebase-tools
          fi

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
