trigger:
  branches:
    include:
      - master
  paths:
    include:
      - backend/*
pool:
  name: Azure Pipelines
steps:
- task: DockerInstaller@0
  displayName: 'Install Docker 26.0.0'
  inputs:
    dockerVersion: 26.0.0

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'sc-docker'
    repository: 'bestengineerpimandek/codingforkids:backend'
    Dockerfile: Dockerfile

- task: AzureCLI@2
  displayName: 'Deploy To Azure Container App'
  inputs:
    azureSubscription: 'sc-azure'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: 'az containerapp update --name ''ca-order-service-ff2u-poc'' --resource-group ''rg-ff2u-poc'' --image ''registry.hub.docker.com/559969/order-management-service-order-service:$(Build.BuildId)'' --set-env-vars BUILD_ID=''$(Build.BuildId)'''
